"""Add priority column

Revision ID: 90792f59f836
Revises: f0a019bee0f4
Create Date: 2024-12-12 20:31:04.513826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90792f59f836'
down_revision = 'f0a019bee0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
